### PR TITLE
DDF-1183: Update to have this module inherit the frontend-maven-plugin v...

### PR DESCRIPTION
**Pull request by ckurata**
...ersions from the parent.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-admin/77)

### CODE REVIEW

**Comment by ckurata** [comment]
@oconnormi, @jckilmer, @lessarderic

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/77)

**Comment by lessarderic** [comment]
Reviewed files:
- ui/pom.xml @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/77)

**Comment by oconnormi** [comment]
Reviewed files:
- ui/pom.xml @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/77)

**Comment by jckilmer** [comment]
Reviewed files:
- ui/pom.xml @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/77)

**Comment by ckurata** [comment]
@phil, @shaun

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/77)

**Comment by shaundmorris** [comment]
Reviewed files:
- ui/pom.xml @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/77)

**Pull request merged**
