### PR TITLE
DDF-1255 , DDF-1256: Fixing issue with branding display, adding logout button

### PR DESCRIPTION
**Pull request by andrewkfiedler**
- Configuration.java: Updated "getProductName" to return product name with version.
- appHeader.handlebars:  Refactored to display better (also fixed issue with branding), added logout.
- style.css:  Refactored appHeader css to handle the new format and the additional logout button.
- application.js:  Updated "setHeader" method to handle the new format of the appHeader, and the additional logout button.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-admin/85)

### CODE REVIEW

**Comment by andrew-fiedler** [comment]
@rzwiefel as hero

**Comment by stustison** [comment]
Can you throw up a screenshot somewhere so we can see it.

**Comment by andrew-fiedler** [comment]
https://drive.google.com/file/d/0B4ZTfmNQAbPJYUthSW14MFp6aWs/view?usp=sharing

**Comment by shaundmorris** [comment]
@andrew-fiedler that looks pretty nice. I like the fix for the version in there too.

**Comment by rzwiefel** [comment]
Pulled, built, tested.. all okay :+1:

**Comment by figliold** [comment]
Merging in pull request for DDF-1255 , DDF-1256: Fixing issue with branding display, adding logout button

**Pull request merged**
