### PR TITLE
DDF-1177: As an Administrator, I need the ability to have a warning bann...

### PR DESCRIPTION
**Pull request by figliold**
...er displayed in the Admin UI when insecure defaults are being used, so that I am warned of a potential security risk
- Added server side code and blacklist for validation

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-admin/71)

### CODE REVIEW

**Comment by figliold** [comment]
@shaundmorris @pklinef @stustison

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/71)

**Comment by stustison** [comment]
<sup>**[core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidator.java, line 171 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-Jo9cGRdYUTihgH5z6L6)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidator.java#L171)):</sup>
We should do the check to see if keystoryPassword == defaultKeystorePassword before performing this step. If it is not using the default it will throw an exception and still send a warning to the user. It seems like there are 3 things to check here to me: 1) does keystoryPassword == defaultKeystorePassword 2) can you open the keystore using the default password even if they don't match and 3) if the passwords don't match, can you open the keystore with the provided password

---

<sup>**[core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/PropertiesFileValidator.java, line 64 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-Jo9e915iF_0TRFJBs-Q)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/PropertiesFileValidator.java#L64)):</sup>
alerts.clear() ? do we actually need to create a brand new list here?

---

<sup>**[core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/SignaturePropertiesFileValidator.java, line 52 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-Jo9eR9DLa93exHCxs0t)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/SignaturePropertiesFileValidator.java#L52)):</sup>
I would think that this should be returning a list that cannot be modified.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/71)

**Comment by pklinef** [comment]
<sup>**[core/admin-core-insecuredefaults/pom.xml, line 15 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoA54vv3eF7WivOZ40y)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/pom.xml#L15)):</sup>
It looks like you used tabs instead of spaces in this pom.

---

<sup>**[core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/CryptoPropertiesFileValidator.java, line 38 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoA5ya6jD0QqARhsS2J)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/CryptoPropertiesFileValidator.java#L38)):</sup>
Just couldn't bring yourself to spell out password?

---

<sup>**[core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidator.java, line 280 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoATezCu0Gm_aXw8A9M)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidator.java#L280)):</sup>
You might be able to simply this method by using CollectionUtils.intersection().  Since you are matching encodings, you might have to look at the Predicate in which case it might not be worth it.  

https://commons.apache.org/proper/commons-collections/javadocs/api-3.2.1/org/apache/commons/collections/CollectionUtils.html#intersection(java.util.Collection, java.util.Collection)

---

<sup>**[core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/PlatformGlobalConfigurationValidator.java, line 55 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoAVgRwsmPJkT3rYdWh)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/PlatformGlobalConfigurationValidator.java#L55)):</sup>
Typo on Disabled

---

<sup>**[core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidatorTest.java, line 61 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoAY_aVmMLzsE4wFetY)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidatorTest.java#L61)):</sup>
I would not check the value of the message with duplicated strings.  I think that will make the tests brittle every time someone changes the messages.  If you want to test this, then I would suggest making constants of the messages and then use something like String.format() to replace placeholders.  Then you test can reuse those constants.

http://docs.oracle.com/javase/1.5.0/docs/api/java/lang/String.html#format%28java.lang.String,%20java.lang.Object...%29

---

<sup>**[core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidatorTest.java, line 82 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoAaZgBCdkxkhzdcl99)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidatorTest.java#L82)):</sup>
If you make message constants, then you can make a list of correct values and then use CollectionUtils.subtract() and check the size to make sure all expected values are present.  Should clean up a lot of test code.

https://commons.apache.org/proper/commons-collections/javadocs/api-3.2.1/org/apache/commons/collections/CollectionUtils.html#subtract(java.util.Collection, java.util.Collection)

---

<sup>**[core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/InsecureDefaultsServiceBeanTest.java, line 57 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoAXpoiHrwXdktbsdIz)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/InsecureDefaultsServiceBeanTest.java#L57)):</sup>
I would simplify the assert logic in this test.  Just call validate twice and make sure the size is correct.  I would not worry about message content in this test.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/71)

**Comment by figliold** [comment]
<sup>**[core/admin-core-insecuredefaults/pom.xml, line 15 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoA54vv3eF7WivOZ40y)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/pom.xml#L15)):</sup>
fixed

---

<sup>**[core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/CryptoPropertiesFileValidator.java, line 38 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoA5ya6jD0QqARhsS2J)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/CryptoPropertiesFileValidator.java#L38)):</sup>
fixed

---

<sup>**[core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidator.java, line 280 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoATezCu0Gm_aXw8A9M)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidator.java#L280)):</sup>
I went down the path of using predicates, but the code looked like it was getting harder to understand. I changed the logic around so the code is more readable.

---

<sup>**[core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/PlatformGlobalConfigurationValidator.java, line 55 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoAVgRwsmPJkT3rYdWh)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/PlatformGlobalConfigurationValidator.java#L55)):</sup>
fixed

---

<sup>**[core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidatorTest.java, line 61 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoAY_aVmMLzsE4wFetY)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidatorTest.java#L61)):</sup>
fixed

---

<sup>**[core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidatorTest.java, line 82 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoAaZgBCdkxkhzdcl99)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidatorTest.java#L82)):</sup>
Didn't use CollectionUtils.subtract(), but used Hamcrest matchers to do something similar.

---

<sup>**[core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/InsecureDefaultsServiceBeanTest.java, line 57 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoAXpoiHrwXdktbsdIz)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/InsecureDefaultsServiceBeanTest.java#L57)):</sup>
fixed

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/71)

**Comment by shaundmorris** [comment]
Reviewed files:
- admin-app/src/main/resources/features.xml @ r1
- core/admin-core-insecuredefaults/pom.xml @ r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/Alert.java @ r1
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/CryptoPropertiesFileValidator.java @ r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidator.java @ r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/InsecureDefaultsServiceBean.java @ r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/InsecureDefaultsServiceBeanMBean.java @ r1
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidator.java @ r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/PaxWebCfgFileValidator.java @ r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/PlatformGlobalConfigurationValidator.java @ r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/PropertiesFileValidator.java @ r1, r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/SignaturePropertiesFileValidator.java @ r1, r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/UsersPropertiesFileValidator.java @ r1, r2
- core/admin-core-insecuredefaults/src/main/java/org/codice/ddf/admin/insecure/defaults/service/Validator.java @ r1
- core/admin-core-insecuredefaults/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r1
- core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/EncryptionPropertiesFileValidatorTest.java @ r1, r2
- core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/InsecureDefaultsServiceBeanTest.java @ r1, r2
- core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/KeystoreValidatorTest.java @ r1, r2
- core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/PaxWebCfgFileValidatorTest.java @ r1, r2
- core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/PlatformGlobalConfigurationValidatorTest.java @ r1, r2
- core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/SignaturePropertiesFileValidatorTest.java @ r1, r2
- core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/UsersPropertiesFileValidatorTest.java @ r1, r2
- core/admin-core-insecuredefaults/src/test/resources/blacklisted.jks @ r1
- core/admin-core-insecuredefaults/src/test/resources/encryptionDefaultAlias.properties @ r1, r2
- core/admin-core-insecuredefaults/src/test/resources/encryptionDefaultPassword.properties @ r1, r2
- core/admin-core-insecuredefaults/src/test/resources/encryptionNondefaults.properties @ r1, r2
- core/admin-core-insecuredefaults/src/test/resources/encryptionWithDefaults.properties @ r1, r2
- core/admin-core-insecuredefaults/src/test/resources/insecureKeystore.jks @ r1
- core/admin-core-insecuredefaults/src/test/resources/insecureTruststore.jks @ r1
- core/admin-core-insecuredefaults/src/test/resources/issuerEncryptionDefaultAlias.properties @ r2
- core/admin-core-insecuredefaults/src/test/resources/issuerEncryptionDefaultPassword.properties @ r2
- core/admin-core-insecuredefaults/src/test/resources/issuerEncryptionNondefaults.properties @ r2
- core/admin-core-insecuredefaults/src/test/resources/issuerEncryptionWithDefaults.properties @ r2
- core/admin-core-insecuredefaults/src/test/resources/org.ops4j.pax.web.cfg @ r1
- core/admin-core-insecuredefaults/src/test/resources/org.ops4j.pax.web.http.disabled.cfg @ r1
- core/admin-core-insecuredefaults/src/test/resources/secureKeystore.jks @ r1
- core/admin-core-insecuredefaults/src/test/resources/secureTruststore.jks @ r1
- core/admin-core-insecuredefaults/src/test/resources/serverEncryptionWithDefaults.properties @ r2
- core/admin-core-insecuredefaults/src/test/resources/serverEncryptionWithNonDefaults.properties @ r2
- core/admin-core-insecuredefaults/src/test/resources/signatureNondefaults.properties @ r1
- core/admin-core-insecuredefaults/src/test/resources/signatureWithDefaults.properties @ r1
- core/admin-core-insecuredefaults/src/test/resources/usersWithDefaults.properties @ r1
- core/admin-core-insecuredefaults/src/test/resources/usersWithNondefaults.properties @ r1
- core/admin-core-insecuredefaults/src/test/resources/usersWithNondefaultsWithAdminUser.properties @ r1
- core/pom.xml @ r1

---

<sup>**[core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/PlatformGlobalConfigurationValidatorTest.java, line 57 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-admin/71#-JoBgEmMVJDF5aVE0FMn)** ([raw file](https://github.com/codice/ddf-admin/blob/caa809a5e6e8b48a74aaced003844f8fef8f168e/core/admin-core-insecuredefaults/src/test/java/org/codice/ddf/admin/insecure/defaults/service/PlatformGlobalConfigurationValidatorTest.java#L57)):</sup>
Agree. I can see where making these alert messages constants would make this more maintainable. But i like the amount of testing here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-admin/71)

**Pull request merged**
